---
title: "Replication of Study 2 by Yang et al. (2018, Psychological Science)"
author: "Yuman Li (yumanl@stanford.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

##Introduction

###Justification for choice of experiment:
The study looks at children's understanding of social norms in cooperation, specifically their evaluation and sanction of free riding phenomenon. The paper is closely related to my research interest in children's social cognitive development. Most of my future work will be around social cognition & child studies, so I would prefer to do a replication on relevant topics.

###Description of Paper:
Across 6 studies, Yang et al.(2018) found that: children as young as 4 year olds negatively evaluate free riders, taking intention into consideration; children's negative valuations towards free riders are not only determined by group impact caused by free riding or nonconformity to the majority; children treat free riders with punishment, but contributors with reward; the similar patterns continue to exist when switching to a situation in which children play as first-parties.

I aim to replicate study 2 for this paper, where the result suggested that 4 to 5-year-olds negatively evaluate free riders. 

###Stimuli and procedures:

All the stimuli can be found on the OSF: [https://osf.io/ke523/](https://osf.io/ke523/)

Stimuli are pictures displayed on a laptop screen, along with the experimenter's description of the story context. Participants were presented with two scenarios in which four members worked together in a group to achieve a common goal. If all four members contributed, the group could get a big reward; if only three of them contributed, the reward would only be a small one. The scenarios have two versions: free rider withholding resources vs. free rider withholding effort. In the former version, donating four chocolates to a piggybank won the group a bigger cake and donating plants into a garden produced more tomatoes. In the latter version, donation was replaced by cleaning the dirty piggybank and growing the tomatoes. Half of the children heared the donation version, and half of them heared the effort version. In terms of intention, each subject heard two scenarios, one involving a free-rider unwilling to contribute (intentional condition), one involving a free-rider willing but unable to contribute (unintentional condition).

The procedures were as below:

-Introduction about the game rules (Memory Check for Children's Understanding of the rules)

-Free riding story - Scenario 1 (Intentional/Unintentional)

-Evaluation/Preference Questions  (Contributor & Free rider)

-Free riding story - Scenario 2 (Unintentional/Intentional)

-Evaluation/Preference Questions  (Contributor & Free rider)


###Anticipated Challenges:
1. Data collection with children will bring me much more work to do than using Amazon Mechanical Turk.

2. Need to connect to Bing Nursery School.

###Links:
Project Repository:  [https://github.com/psych251/yang2018](https://github.com/psych251/yang2018)

Original Paper:  [https://github.com/psych251/yang2018/tree/master/OriginalPaper](https://github.com/psych251/yang2018/tree/master/OriginalPaper)


##Methods

###Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.  (to be filled)

###Planned Sample

Based on original paper and suggestions from the original author, the planned sample size will be 32 participants (4 to 5-year-olds) from Stanford Bing Nursery School. 

###Materials

Materials below are quoted directly from original article:

"We presented each participant with two scenarios in which a four-member group could obtain a large reward if all four members contributed to a collective goal or a smaller reward if only three members contributed. The scenarios were described verbally by the experimenter and depicted through pictures on a laptop display. One scenario involved a magic piggy bank modeled after a public-goods game in which placing chocolates in a piggy bank would lead to the appearance of a cake that was then shared among the group. The other scenario involved a more naturalistic gardening setting in which placing plants in a garden produced tomatoes. Each participant heard both scenarios, one involving an unwilling free rider (intentional-free-riding condition) and one involving a willing but unable free rider (unintentional-free-riding condition). Key conditions and scenes are represented in Figure 1. To establish a modicum of generality, we investigated two types of free riding (withholding of a valuable resource versus withholding of effort). Half of the participants heard a donation version of the story (i.e., donate chocolate to the piggy bank and donate plants to the garden), and the other half of participants heard an effort version (i.e., clean the dirty piggy bank and grow the tomatoes). The type of free riding (withholding of resources versus effort) was thus manipulated between subjects, and across subjects, all pairings among scenario, type of free riding, and intentionality were included."

Note: this will be followed precisely in the replication study.

###Procedure	

The procedure below is quoted directly from original article:

"During testing, children were first introduced to the groups and told how the piggy bank or garden worked in terms of the rewards (i.e., get a bigger cake or basket of tomatoes with contributions from four members vs. three members). As a memory check, children were asked at the end of this familiarization phase about which reward the group would get if three versus four members contributed and all children answered the questions correctly. After familiarization, in the intentional-free-riding condition (Fig. 1a), children were shown through animations that the free rider kept the resources for themselves or made no actions. In the unintentional-free-riding condition (Fig. 1b), the free riders wanted to donate or make an effort to the group, but their resource was eaten by a pet (donation version) or they could not do the work because of an injury (effort version). In both conditions, the contributors put in the resources or made the actions. Finally, children were shown that the group got the second-best reward, and each child target got a small but equal share of the group reward. Children were asked to rate the free rider and one of the contributors on a 4-point scale indicating (a) how good or bad each character was (judgment question) and (b) how much they liked or disliked each character (preference question). At the end of the session, children were asked two memory questions about (a) whether the group received the bigger or the smaller reward (outcome question) and (b) whether three or four people contributed to the group (action question)."

Note: this will be followed precisely in the replication study.

###Analysis Plan

The procedure below is quoted directly from original article:

"All children answered the memory questions correctly. Children’s judgment and preference ratings ranged from 1 (most negative) to 4 (most positive). Preliminary results indicated no differences between the two types of scenario (piggy bank vs. gardening), the type of free riding (effort vs. donation), or the type of question (judgment vs. preference), so we collapsed across these factors in primary analyses. We used children’s judgment and preference ratings as indicators for evaluation ratings and analyzed data via mixed linear models predicting children’s ratings as a function of target (dummy coded; free rider vs. contributor), intentionality (dummy coded; whether the scenario involved intentional vs. unintentional free riding), child age, and the interactions among them, with a random intercept for participant. Data and code to replicate all analyses reported in this article are available at [https://osf.io/g8xyt/](https://osf.io/g8xyt/)."

**Clarify key analysis of interest here**  

Using a linear mixed regression model to test whether the identity of the target (free rider vs. contributor), intentionality, and interactions between these two variables predict children's ratings.

###Differences from Original Study

1. The origianl study was conducted in a campus lab at Yale, at schools and at a local museum in New Haven, CT. But this study will be conducted at Stanford Nursery School in Palo Alto, CA, specifically in an ad hoc game room. Not sure whether there will be any differences between children from The East and West Coast of the United States in a big scope, but the change of specific rooms should be fine according to the author's notes in the original paper.

2. The majority of children in the original studies were from middle-class families and of European American ethnicity (> 75%). Bing Nursery School, with a mission of providing a laboratory setting for research in developmental psychology, may have more diversified-background children in this aspect. I will check the children's demographic information as I collect data.

3. Another difference is that I will run the experiment myself. The original study seemed to be run by several experimenters or research assistants. I have got the protocol from the original author, but minor differences will still be inevitable. 

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


##Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
###Data Preparation

####Load Relevant Libraries and Functions

####Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

###Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
